/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rent;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Thili
 */
public class rental extends javax.swing.JFrame {

    /**
     * Creates new form rental
     */
    public rental() {
        initComponents();
        loadcar();
        
        
        txtdate.setDateFormatString("yyyy/MM/dd");
        txtdue.setDateFormatString("yyyy/MM/dd");
        
    }
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    
    PreparedStatement pst2;
    PreparedStatement pst3;
    
    public void loadcar(){
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rent","root","");
            pst=(PreparedStatement) con.prepareStatement("select * from carregistration");
            
            ResultSet rs = pst.executeQuery();
            combocarid.removeAllItems();
            
            while(rs.next())
            {
               combocarid.addItem(rs.getString(2));
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combocarid = new javax.swing.JComboBox<>();
        txtcustid = new javax.swing.JTextField();
        txtcustname = new javax.swing.JTextField();
        txtrentalfee = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtdue = new com.toedter.calendar.JDateChooser();
        btnok = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtavl = new javax.swing.JTextField();
        btnenter = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Car Id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 160, 114, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 220, 114, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 290, 114, 27);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Rental Fee");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 340, 87, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 410, 60, 36);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Due Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 480, 87, 27);

        combocarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocaridActionPerformed(evt);
            }
        });
        combocarid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combocaridKeyPressed(evt);
            }
        });
        jPanel1.add(combocarid);
        combocarid.setBounds(410, 160, 114, 39);

        txtcustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustidActionPerformed(evt);
            }
        });
        txtcustid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcustidKeyPressed(evt);
            }
        });
        jPanel1.add(txtcustid);
        txtcustid.setBounds(410, 220, 180, 34);

        txtcustname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtcustname);
        txtcustname.setBounds(410, 290, 180, 31);

        txtrentalfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrentalfeeActionPerformed(evt);
            }
        });
        jPanel1.add(txtrentalfee);
        txtrentalfee.setBounds(580, 340, 122, 37);
        jPanel1.add(txtdate);
        txtdate.setBounds(410, 410, 180, 36);
        jPanel1.add(txtdue);
        txtdue.setBounds(410, 480, 180, 30);

        btnok.setBackground(new java.awt.Color(255, 255, 255));
        btnok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnok.setForeground(new java.awt.Color(51, 51, 255));
        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        btnok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnokKeyPressed(evt);
            }
        });
        jPanel1.add(btnok);
        btnok.setBounds(230, 580, 53, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(410, 580, 65, 40);

        txtavl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtavlActionPerformed(evt);
            }
        });
        jPanel1.add(txtavl);
        txtavl.setBounds(580, 160, 122, 40);

        btnenter.setText("Enter");
        btnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenterActionPerformed(evt);
            }
        });
        btnenter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnenterKeyPressed(evt);
            }
        });
        jPanel1.add(btnenter);
        btnenter.setBounds(410, 340, 114, 37);

        btnclear.setBackground(new java.awt.Color(255, 255, 255));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(51, 51, 255));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(590, 580, 67, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rent/Vehicles (158).JPG"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(740, 40, 600, 540);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Rental");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 39, 190, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combocaridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocaridActionPerformed
        
        String id = combocarid.getSelectedItem().toString();
//            
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rent","root","");
            
            pst = (PreparedStatement) con.prepareStatement("select * from carregistration where car_no = ?");
            pst.setString(1, id);
            
            ResultSet ra = pst.executeQuery();
            

                
            if (ra.next() == false) {
                JOptionPane.showMessageDialog(this, "Car is Not Available");
            }else{
                String avl = ra.getString("available");
                txtavl.setText(avl.trim());            
                
                if (avl.equals("Yes")) {
//                    txtCusID.setEnabled(false);
                    txtcustname.setEnabled(true);
                    txtcustid.setEnabled(true);
                    txtdate.setEnabled(true);
                    txtdue.setEnabled(true);
                   
                }
            }
                   
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_combocaridActionPerformed

    private void txtcustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustidActionPerformed

    private void txtcustidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustidKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER )
      {
          String cust_id = txtcustid.getText();
          try {
              Class.forName("com.mysql.jdbc.Driver");
              con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rent","root","");
              pst1=(PreparedStatement) con.prepareStatement("select * from customer where custom_id=?");
              pst1.setString(1, cust_id);
              ResultSet rs = pst1.executeQuery();
              
              if (rs.next()== false) {
              
                JOptionPane.showMessageDialog(this, "Customer no is Not Available");
                                      
                }
              else
              {
                  String custname = rs.getString("custom_name");
                  txtcustname.setText(custname.trim());
                  
                  }
              
              
              
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
          }
          
         
      }
    }//GEN-LAST:event_txtcustidKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Maindoc m = new Maindoc();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        String car_id;
        car_id = combocarid.getSelectedItem().toString();
        String cust_id=txtcustid.getText();
        String fee=txtrentalfee.getText();
                     
        SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
        String date=Date_Format.format(txtdate.getDate());
        
        SimpleDateFormat Date_Format1 = new SimpleDateFormat("yyyy-MM-dd");
        String due=Date_Format1.format(txtdue.getDate());
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rent","root","");
            pst2=(PreparedStatement) con.prepareStatement("insert into carrental(car_id,custom_id,fee,date,due)values (?,?,?,?,?)");
            pst2.setString(1, car_id);
            pst2.setString(2, cust_id);
            pst2.setString(3, fee);
            pst2.setString(4, date);
            pst2.setString(5, due);
            pst2.executeUpdate();
            
            pst3 = (PreparedStatement) con.prepareStatement("update carregistration set available='Not' where car_no=?");
            pst3.setString(1, car_id);
            pst3.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Successs");
            
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_btnokActionPerformed

    private void txtavlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtavlActionPerformed
       String avl = txtavl.getText();
          try {
              Class.forName("com.mysql.jdbc.Driver");
              con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rent","root","");
              pst1=(PreparedStatement) con.prepareStatement("select * from carregistration where car_no=?");
              pst1.setString(1, avl);
              ResultSet rs = pst1.executeQuery();
              
              pst3 = (PreparedStatement) con.prepareStatement("update carregistration set available='Not' where car_no=?");
              pst3.setString(1, avl);
              pst3.executeUpdate();
              
              
              
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_txtavlActionPerformed

    private void combocaridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combocaridKeyPressed
        
    }//GEN-LAST:event_combocaridKeyPressed

    private void btnenterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnenterKeyPressed
        
    }//GEN-LAST:event_btnenterKeyPressed

    private void txtrentalfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrentalfeeActionPerformed
        
    }//GEN-LAST:event_txtrentalfeeActionPerformed

    private void btnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenterActionPerformed
       String enter = btnenter.getText();
          try {
              Class.forName("com.mysql.jdbc.Driver");
              con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/rent","root","");
              
              String car_id=(String) combocarid.getSelectedItem();
              
              pst=(PreparedStatement) con.prepareStatement("select car_no,car_fee from carregistration where car_no=?");
              pst.setString(1, car_id);
              ResultSet rs = pst.executeQuery();
              
              if (rs.next()== false) {
              
                JOptionPane.showMessageDialog(this, "Car is Not Found  ");
                                      
                }
              else
              {
                  String car_fee = rs.getString("car_fee");
                  txtrentalfee.setText(car_fee.trim());
                  
              }
              
              
              
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(rental.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnenterActionPerformed

    private void btnokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnokKeyPressed
        
    }//GEN-LAST:event_btnokKeyPressed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtavl.setText("");
        txtcustid.setText("");
        txtcustname.setText("");
        txtrentalfee.setText("");
        txtdate.setDateFormatString("");
        txtdue.setDateFormatString("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtcustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnenter;
    private javax.swing.JButton btnok;
    private javax.swing.JComboBox<String> combocarid;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtavl;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtcustname;
    private com.toedter.calendar.JDateChooser txtdate;
    private com.toedter.calendar.JDateChooser txtdue;
    private javax.swing.JTextField txtrentalfee;
    // End of variables declaration//GEN-END:variables
}
